import { DateTime } from 'luxon'
import { describe, expect, it } from 'vitest'
import { getDayProfile, getHourlySummary } from './dayProfile'
import { getSolarMaximum } from './dayStatistics'
import { getSunEvents } from './sunEvents'
import { getSunRate, shortestAngularDifference } from './sunRate'
import { getSunPosition } from './sunPosition'
import type { Location } from './types'

const usti: Location = {
  name: 'Ústí nad Labem',
  latitude: 50.6724,
  longitude: 14.0706,
  elevationMeters: 0,
  timezone: 'Europe/Prague',
}

describe('solar position', () => {
  it('is physically plausible on 2026-08-16', () => {
    const midnight = getSunPosition(
      usti,
      DateTime.fromISO('2026-08-16T00:00', { zone: usti.timezone }).toJSDate(),
    )
    const noon = getSunPosition(
      usti,
      DateTime.fromISO('2026-08-16T13:00', { zone: usti.timezone }).toJSDate(),
    )

    expect(midnight.altitudeDeg).toBeLessThan(0)
    expect(noon.altitudeDeg).toBeGreaterThan(40)
    expect(noon.azimuthDeg).toBeGreaterThanOrEqual(0)
    expect(noon.azimuthDeg).toBeLessThan(360)
  })

  it('calculates daytime shadow geometry and suppresses it at night', () => {
    const noon = getSunPosition(usti, new Date('2026-08-16T11:00:00Z'))
    const night = getSunPosition(usti, new Date('2026-08-15T22:00:00Z'))

    expect(noon.shadowLengthFactor).not.toBeNull()
    expect(noon.shadowLengthFactor).toBeGreaterThan(0)
    expect(noon.shadowAzimuthDeg).toBeCloseTo((noon.azimuthDeg + 180) % 360, 8)
    expect(night.shadowLengthFactor).toBeNull()
    expect(night.shadowAzimuthDeg).toBeNull()
  })
})

describe('solar movement rate', () => {
  it('uses the shortest signed path through azimuth wraparound', () => {
    expect(shortestAngularDifference(359.9, 0.1)).toBeCloseTo(0.2, 8)
    expect(shortestAngularDifference(0.1, 359.9)).toBeCloseTo(-0.2, 8)
  })

  it('has positive morning and negative afternoon altitude rate', () => {
    const morning = getSunRate(usti, new Date('2026-08-16T07:00:00Z'))
    const afternoon = getSunRate(usti, new Date('2026-08-16T15:00:00Z'))

    expect(morning.altitudeDegPerMinute).toBeGreaterThan(0)
    expect(afternoon.altitudeDegPerMinute).toBeLessThan(0)
  })

  it('is near zero at solar culmination', () => {
    const solarNoon = getSunEvents(usti, '2026-08-16').solarNoon

    expect(solarNoon).not.toBeNull()
    expect(Math.abs(getSunRate(usti, solarNoon!).altitudeDegPerMinute)).toBeLessThan(0.001)
  })
})

describe('day events', () => {
  it('returns twilight and daylight events in chronological order', () => {
    const events = getSunEvents(usti, '2026-08-16')
    const required = [
      events.astronomicalDawn,
      events.nauticalDawn,
      events.civilDawn,
      events.sunrise,
      events.solarNoon,
      events.sunset,
      events.civilDusk,
      events.nauticalDusk,
      events.astronomicalDusk,
    ]

    required.forEach((event) => expect(event).not.toBeNull())
    for (let index = 1; index < required.length; index += 1) {
      expect(required[index]!.getTime()).toBeGreaterThan(required[index - 1]!.getTime())
    }
    expect(events.dayLengthSeconds).toBeGreaterThan(12 * 60 * 60)
    expect(events.dayLengthSeconds).toBeLessThan(18 * 60 * 60)
  })

  it('keeps the installed Astronomy Engine culmination result stable', () => {
    const events = getSunEvents(usti, '2026-08-16')

    expect(events.solarNoon).not.toBeNull()
    // Regression fixture generated by astronomy-engine 2.1.19, not an independent reference.
    expect(Math.abs(events.solarNoon!.getTime() - Date.parse('2026-08-16T11:08:01.769Z'))).toBeLessThan(1_000)
  })
})

describe('day statistics', () => {
  it('uses the exact culmination instant for maximum time and altitude', () => {
    const solarNoon = getSunEvents(usti, '2026-08-16').solarNoon
    const maximum = getSolarMaximum(usti, solarNoon)

    expect(maximum).not.toBeNull()
    expect(maximum!.timestamp).toEqual(solarNoon)
    // Regression fixture generated by astronomy-engine 2.1.19, not an independent reference.
    expect(maximum!.altitudeDeg).toBeCloseTo(52.98624, 4)
  })

  it('returns null when no culmination is available', () => {
    expect(getSolarMaximum(usti, null)).toBeNull()
  })
})

describe('civil-day profiles', () => {
  it('samples every instant in a normal local day', () => {
    const samples = getDayProfile(usti, '2026-08-16')

    expect(samples).toHaveLength(288)
    expect(DateTime.fromJSDate(samples[0].timestamp, { zone: usti.timezone }).toFormat('HH:mm')).toBe('00:00')
    expect(samples.some((sample) => sample.altitudeDeg > 40)).toBe(true)
  })

  it('uses 23 hours on the spring DST transition', () => {
    expect(getDayProfile(usti, '2026-03-29')).toHaveLength(276)
  })

  it('uses 25 hours on the autumn DST transition', () => {
    expect(getDayProfile(usti, '2026-10-25')).toHaveLength(300)
  })

  it('builds an hourly summary with altitude deltas and rates', () => {
    const summary = getHourlySummary(usti, '2026-08-16')

    expect(summary).toHaveLength(24)
    expect(summary[0].deltaFromPreviousHour).toBeNull()
    expect(summary[1].deltaFromPreviousHour).toBeCloseTo(
      summary[1].altitudeDeg - summary[0].altitudeDeg,
      8,
    )
    expect(summary[1].averageRateDegPerHour).toBeCloseTo(summary[1].deltaFromPreviousHour!, 8)
  })

  it('builds 23 real hourly samples on the spring DST transition', () => {
    expect(getHourlySummary(usti, '2026-03-29')).toHaveLength(23)
  })

  it('builds 25 distinguishable hourly samples on the autumn DST transition', () => {
    const summary = getHourlySummary(usti, '2026-10-25')
    const repeatedHour = summary.filter((sample) => sample.hour === '02:00')

    expect(summary).toHaveLength(25)
    expect(repeatedHour).toHaveLength(2)
    expect(repeatedHour[1].timestamp.getTime() - repeatedHour[0].timestamp.getTime()).toBe(3_600_000)
    expect(repeatedHour.map((sample) => sample.utcOffset)).toEqual(['+02:00', '+01:00'])
  })
})
