import { formatClock, formatDuration } from '../astronomy/formatting'
import type { AltitudeCrossings, Location } from '../astronomy/types'
interface AltitudeMilestonesProps { location: Location; crossings: AltitudeCrossings[]; now: Date; observationLabel: string; altitudeRateDegPerMinute: number; onInspect: (instant: Date) => void }
export function AltitudeMilestones({ location, crossings, now, observationLabel, altitudeRateDegPerMinute, onInspect }: AltitudeMilestonesProps) {
  const future = crossings.flatMap((crossing) => [crossing.rising ? { altitude: crossing.altitudeDeg, direction: 'rising', time: crossing.rising } : null, crossing.descending ? { altitude: crossing.altitudeDeg, direction: 'descending', time: crossing.descending } : null]).filter((item): item is { altitude: number; direction: string; time: Date } => Boolean(item && item.time.getTime() > now.getTime())).sort((a, b) => a.time.getTime() - b.time.getTime())
  const next = future[0]
  const direction = Math.abs(altitudeRateDegPerMinute) < 0.001 ? 'at culmination' : altitudeRateDegPerMinute > 0 ? 'rising' : 'descending'
  const crossingCell = (time: Date | null, label: string) => <td>{time ? <button className={`data-target ${Math.abs(time.getTime() - now.getTime()) <= 1_000 ? 'selected' : ''}`} aria-pressed={Math.abs(time.getTime() - now.getTime()) <= 1_000} aria-label={`Inspect ${label} at ${formatClock(time, location.timezone)}`} onClick={() => onInspect(time)}>{formatClock(time, location.timezone)}</button> : '—'}</td>
  return <article className="panel milestones-panel"><div className="panel-heading"><div><span className="section-kicker">Refined apparent-altitude crossings</span><h2>Altitude milestones</h2></div><span className="tempo-unit">second-level search</span></div><div className="milestone-live"><span>{observationLabel}: Sun is {direction}</span><strong>{next ? `Next: ${next.altitude}° ${next.direction} in ${formatDuration((next.time.getTime() - now.getTime()) / 1000, true)}` : 'No remaining milestone today'}</strong></div><div className="table-wrap"><table><thead><tr><th>Altitude</th><th>Rising</th><th>Descending</th></tr></thead><tbody>{crossings.map((crossing) => <tr key={crossing.altitudeDeg}><td>{crossing.altitudeDeg}°</td>{crossingCell(crossing.rising, `${crossing.altitudeDeg}° rising crossing`)}{crossingCell(crossing.descending, `${crossing.altitudeDeg}° descending crossing`)}</tr>)}</tbody></table></div></article>
}
